### ISSUE TITLE
Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

### ISSUE THREAD

**Issue by VolVoz** [autocomplete-python/autocomplete-python#176]
In styles/autocomplete-python.less: Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.
If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

**Comment by sadovnychyi** [comment]
Could you explain a bit more why is it important so? Maybe link on the docs or something?

Are you suggesting just to replace `atom-text-editor` with `atom-text-editor::shadow`?
