### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by pchomik** [autocomplete-python/autocomplete-python#195]
I'd like to highlight that autocomplete-python has biggest startup time in my atom configuration. Based on Timecop the time is 79ms and is marked as red. Most packages has startup lower that 20ms. Package activation looks nice 7ms.

It will be nice to improve startup time and keep it on good level. To much such slow starting plugins may become annoying for atom users.

**Comment by walles** [comment]
Re-broken by https://github.com/autocomplete-python/autocomplete-python/commit/658551a299586c45055f2390db7bd4ec783909fd

Refix code or reopen issue?

**Comment by 50Wliu** [comment]
It takes 1200ms here, which is 3-4x as long as the second-slowest package.

**Comment by walles** [comment]
@dhung09, could you write something about what problem you wanted to solve by removing the `activationHooks` in https://github.com/autocomplete-python/autocomplete-python/commit/658551a299586c45055f2390db7bd4ec783909fd?

Maybe that problem could be solved in some other way that doesn't have as much impact on startup time?

**Comment by dev169** [comment]
Noticed this as well. 

```
Activated 79 packages in 2883ms. 29 packages took longer than 5ms to activate.
autocomplete-python 1801ms
project-plus 282ms
tab-control 245ms
status-bar 94ms
<snip>
```

**Comment by dhung09** [comment]
Hi guys, thanks for bringing up this issue. We need autocomplete-python to activate at startup so unfortunately `activationHooks` has to be removed. However, we realize slow startup times is certainly undesired so we're working on optimizing the `activate` function to something more reasonable for our users. We will keep you posted but expect to see a change within the week

**Comment by walles** [comment]
@dhung09, *why* do we "need autocomplete-python to activate at startup"?

**Comment by dhung09** [comment]
Hi @walles, autocomplete-python recently added support to use [Kite](https://kite.com/faq-autocomplete-python/) as its completions engine and `activationHooks` was removed to allow the user to (optionally) install Kite when the plugin was installed/updated so as not to interrupt the user while he was actually coding.

Kite is currently only supported on macOS but we're working hard on getting Windows and Linux support up. For those who don't want to/can't use Kite, autocomplete-python will continue to support the Jedi engine.

To address slow startup, #261 should get the activation time to something much more reasonable (~10ms on my machine)
