### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value

### ISSUE THREAD

**Issue by maurerv** [autocomplete-python/autocomplete-python#202]
Using autocomplete-python on Windows, I find the process hierarchy within Atom "atom.exe > cmd.exe > python.exe", where python is running ".atom\packages\autocomplete-python\lib/completion.py". When the 10min timeout hits, only "cmd.exe" dies leaving the python process without any parent. Python then spams its stderr with the traceback:

```
Traceback (most recent call last):
  File "C:\Users\maurerv\.atom\packages\autocomplete-python\lib/completion.py", line 340, in watch
    self._process_request(self._input.readline())
  File "C:\Users\maurerv\.atom\packages\autocomplete-python\lib/completion.py", line 302, in _process_request
    request = self._deserialize(request)
  File "C:\Users\maurerv\.atom\packages\autocomplete-python\lib/completion.py", line 277, in _deserialize
    return json.loads(request)
  File "d:\Python3\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "d:\Python3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "d:\Python3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

It seems `JediCompletion.watch` does not cope well with a closed `_input` and is trying to process empty strings.

System: Windows 7
Atom version: 1.7.1
autocomplete-python version: 1.7.2
Python version: 3.5.1

**Comment by sadovnychyi** [comment]
Hey. Good catch, thanks for this.

I didn't test process killing properly on windows. Will definitely do it once I got some time.

**Comment by sadovnychyi** [comment]
https://github.com/atom/atom/blob/master/src/buffered-process.coffee#L185-L192

It's actually should be killed according to this Atom's wrapper around child process.
Is it possible that platform isn't set properly on your system? Or maybe it's a bug in Atom's buffered process.

**Comment by maurerv** [comment]
Ah I thought there would be more to this. So platform is all set and the correct method of BufferedProcess is called, but somehow it fails to correctly spawn wmic to get the child process ids to kill, despite clearly having it in the PATH.

However, when I start Atom from MSYS2 everything works - from cmd or the taskbar it exhibits the behavior above. So I guess it is probably a problem with my system's environment. (The notorious reboot does not help, however)

Anyway, thank you for taking a look.
