### ISSUE TITLE
autocomplete-python opens multiple instances of python

### ISSUE THREAD

**Issue by mostaphaRoudsari** [autocomplete-python/autocomplete-python#205]
![autocomplete_python](https://cloud.githubusercontent.com/assets/2915573/15033546/bf18f8a6-1239-11e6-82f9-4fb3ef8e5ad2.PNG)

It happens even when I'm not directly working in atom but have it open on my computer.

Windows 8 and Atom 1.7.3.

**Comment by evildarkarchon** [comment]
I also have the same problem on windows 10 with python 3.5.1, I've had my system slow to a crawl just from leaving atom up with this package installed and active.

**Comment by sadovnychyi** [comment]
It's supposed to be one python process per atom window. And they supposed
to be killed after 15 minutes if inactivity. Can you confirm that they stay
after 15 minutes you didn't use auto complete? Maybe it's not getting
killed properly.

**Comment by sadovnychyi** [comment]
Can you check possible solution from here?
https://github.com/sadovnychyi/autocomplete-python/issues/202#issuecomment-210792599

**Comment by mostaphaRoudsari** [comment]
Hi @sadovnychyi! Thanks. I'm not sure which solution you're referring to. Is there a way to set the platform for Atom? I can confirm that ```sys.platform``` returns ```win32```.

To have python instances open by itself is not a problem as far as they are not taking too much processing power. Is it normal that they are taking too much computing power even when I'm not using the editor?

**Comment by mostaphaRoudsari** [comment]
Opening from cmd seems to solve the problem. @sadovnychyi seems to be an issue with atom not setting up the platform correctly but why this only happens for this package?

**Comment by sadovnychyi** [comment]
Well there's no much packages which spawn external processes I guess. Somebody should probably open an issue in Atom about it not killing processes properly on windows. 

There's still a question why you can see process activity in IDLE state though.

Can you please turn on debug logs in package settings and look in developer console, is there are any logs from autocomplete-python when it eats your resources?

**Comment by mostaphaRoudsari** [comment]
I have other packages like python-tools installed that does follow a similar approach but then it kills the python.exe.

I tested it in the debug mode. At least autocomplete-python tires to kill python process but I can still see them in the process. For now I just kill them manually.

```javascript
/C:/Users/Administrator/.atom/packages/autocomplete-python/lib/log.coffee:10
autocomplete-python: Got 1 lines
/C:/Users/Administrator/.atom/packages/autocomplete-python/lib/log.coffee:10
autocomplete-python: Cached request with ID fd15de23c8409bfc852c77fa4d5c8c2b
/C:/Users/Administrator/.atom/packages/autocomplete-python/lib/log.coffee:10
autocomplete-python: Killing python process after timeout...
```

I have to kill them manually.

**Comment by sadovnychyi** [comment]
Strange. python-tools uses copy-pasted code from older version of autocomplete-python, and it's uses the same method to kill the process: https://github.com/MichaelAquilina/python-tools/blob/master/lib/python-tools.coffee#L125 But it does not kill process on timeout, only when you deactivate the package.

**Comment by evildarkarchon** [comment]
Just tested running atom through bash and it seems to kill the process properly there.

**Comment by mostaphaRoudsari** [comment]
I can confirm that there is no log from autocomplete-python for open instances. It makes sense since it assumes they have been already killed.

**Comment by lrecknagel** [comment]
I can confirm this on Atom for OSX. It opens multiple instances and they also cannot termiated and stay in the Dock.

**Comment by sadovnychyi** [comment]
@lrecknagel that's really strange, since in osx it does not create any extra processes. Can you confirm that the same thing happening in the logs?

**Comment by lrecknagel** [comment]
@sadovnychyi they are not shown in the activity monitor, they only appearing in the Dock. Over 1 hour of coding 5 to 9 instances are opened. On rightclick OSX tell that they are not responding. So its probably another issue?!

**Comment by sadovnychyi** [comment]
Why they are appearing in the dock? Do you have any kind of special python or something? This is definitely not supposed to happen. Can you show a screenshot?

**Comment by sadovnychyi** [comment]
And, well, if they are not appearing in the activity monitor -- this is really strange. Can you find them there before it was killed? If you can find them there before and cannot after they are killed – it's probably something in your system.

**Comment by lrecknagel** [comment]
I tested again and now they are in the activity monitor, until i kill them:
<img width="584" alt="screenshot 2016-05-12 11 08 49" src="https://cloud.githubusercontent.com/assets/3778089/15209564/03521aae-1832-11e6-8192-e53c165ba9e5.png">

Here are the behaviour in the dock:
<img width="188" alt="screenshot 2016-05-12 11 07 17" src="https://cloud.githubusercontent.com/assets/3778089/15209533/d167b2e2-1831-11e6-8023-e38b15d2d2aa.png">
<img width="393" alt="screenshot 2016-05-12 11 07 22" src="https://cloud.githubusercontent.com/assets/3778089/15209534/d1681e62-1831-11e6-8029-44879f5f10c7.png">
<img width="312" alt="screenshot 2016-05-12 11 07 29" src="https://cloud.githubusercontent.com/assets/3778089/15209532/d164a110-1831-11e6-8f96-5ecbfceda2bc.png">

**Comment by lrecknagel** [comment]
Are there any new insights for this problemß I hope there will be a fix soon.

**Comment by sadovnychyi** [comment]
Sorry, didn't look on it. I actually have a VM with windows now, will try to reproduce it.

**Comment by sadovnychyi** [comment]
If you are talking about OSX though I never saw it here. I'm on El Capitan. And I run Atom from both terminal and dock.

**Comment by lrecknagel** [comment]
Yeah talking about OSX. Its really crazy that I am the only one who have this issue. But I can confirm it for OSX El Capitain because if I deactivate this package the problem goes away.
If I force quit the processes I get this log message in the Atom Console:

![screenshot 2016-06-22 14 12 21](https://cloud.githubusercontent.com/assets/3778089/16266309/7186b666-3884-11e6-8ab4-ec5837fa7b4d.png)

**Comment by sadovnychyi** [comment]
Can you try to run this from atom console?
```javascript
BufferedProcess = require("atom").BufferedProcess
proc = new BufferedProcess({
  command: 'python',
  args: ['-c', 'import time;time.sleep(10);'],
})
proc.kill()
```
Can you see such process in the dock like the one created with autocomplete-python? Can you check if it's killed properly or not? You may want to make it sleep more so it won't terminate itself.

**Comment by lrecknagel** [comment]
I tried it and nothing happens, also in my activity monitor no new python instance showing up when I execute that :/

**Comment by sadovnychyi** [comment]
You may want to change "python" to full path to pytho nexecutable, like on your screenshot. Also type "proc" and check process.signalCode (also visible on your screenshot)

**Comment by lrecknagel** [comment]
I run:
```javascript
BufferedProcess = require("atom").BufferedProcess
proc = new BufferedProcess({
  command: 'PATH_TO_VIRTUALENV/tv2-env/bin/python',
  args: ['-c', 'import time;time.sleep(10);'],
})
console.log(proc.process.signalCode); proc.kill();
```

output is: null. So it has no signalCode set

**Comment by mostaphaRoudsari** [comment]
I don't see this issue anymore on my machine. Not sure why. I both updated Windows and pythontools package for atom. Now it works as expected.

**Comment by sadovnychyi** [comment]
@mostaphaRoudsari thanks for update. I have no idea what to do with it, glad it works now though.

**Comment by sadovnychyi** [comment]
Please create new issue if it's still happening in 1.8.10.
