### ISSUE TITLE
fresh install autocomplete 1.7.2 freezes after typing single character

### ISSUE THREAD

**Issue by derwentx** [autocomplete-python/autocomplete-python#208]
Hey, 

i am running atom 1.7.3, autocomplete 1.7.2, python 2.7.10 on a MacBookPro11,3 with OS X 10.11.4 (15E65)

every time i type a single character into a python source file, my CPU usage goes to 100% and the atom window locks up until i force quit it. this goes away when i disable autocomplete.

i'm quite new to atom so i don't know what debugging into i can provide you right off the bat, so let me know what would help.

other plugins (latest versions as of today) 

```
Parinfer
atom-term2
autocomplete-python
highlight-selected
ink
linter
linter-pylint
lisp-paredit
proto-repl
script
set-syntax
term3
tool-bar
```

thanks

**Comment by sadovnychyi** [comment]
Go to autocomplete-python settings and turn on debug logging. Then open dev tools from command palette and open Console tab. Look for related log output.

There's nothing I can do if it's freezes before showing up anything. Maybe you got a giant project and Jedi tries to index it?

**Comment by derwentx** [comment]
Here we go, the log has this repeating forever

```
autocomplete-python: Using interpreter /usr/local/lib/python2.6
log.coffee:5 autocomplete-python: Pending requests: 0 Object {}
log.coffee:5 autocomplete-python: Spawning python process...
log.coffee:5 autocomplete-python: No user defined interpreter found, trying automatic lookup
log.coffee:5 autocomplete-python: Project level interpreters found Set {}
log.coffee:5 autocomplete-python: Total automatically found interpreters Set {"/usr/local/lib/python2.6", "/usr/local/lib/python2.7", "/usr/local/lib/python3.5", "/usr/local/bin/python3", "/usr/local/bin/python3.5"…}
```

**Comment by derwentx** [comment]
fixed it by setting my interpreter manually, but i believe crashing on default settings isn't intended behaviour so this is probably still something to be fixed :P happy to test new builds on my system if you believe you've found the source of this infinite loop!

**Comment by sadovnychyi** [comment]
So after those log entries they repeat starting from `Using interpreter /usr/local/lib/python2.6` again?

**Comment by phyllisstein** [comment]
I had the same problem, but eventually realized I had incorrectly configured the package by dropping the actual executable from the list of executable paths. (That is, adding `$PROJECT/.direnv/python-3.5.2/bin` instead of `$PROJECT/.direnv/python-3.5.2/bin/python`.) Suspect that `/usr/local/lib/python2.6` in your paths could be wreaking similar havoc.

**Comment by sadovnychyi** [comment]
I don't see any ways to improve here, missing configurations *shouldn't* hang your editor and I cannot reproduce this on my machine. It's possible though if you have really big number of folders and it tries to scan them to find python executable.

**Comment by fishcorn** [comment]
I ran into the same issue and fixed it by repeating what @phyllisstein did. 

I also got the infinite loop, but I wanted to add the console output to see if that's useful to you.
```
...
log.coffee [sm]:5 autocomplete-python: Spawning python process...
log.coffee [sm]:5 autocomplete-python: User defined interpreters found 
Set {"/home/john/anaconda2/bin"}
log.coffee [sm]:5 autocomplete-python: Using interpreter /xxx/anaconda2/bin
log.coffee [sm]:5 autocomplete-python: Pending requests: 0 
Object {}
log.coffee [sm]:5 autocomplete-python: Spawning python process...
log.coffee [sm]:5 autocomplete-python: User defined interpreters found 
Set {"/home/john/anaconda2/bin"}
log.coffee [sm]:5 autocomplete-python: Using interpreter /xxx/anaconda2/bin
log.coffee [sm]:5 autocomplete-python: Pending requests: 0 
Object {}
...
```

**Comment by sadovnychyi** [comment]
Related #251
