### ISSUE TITLE
100 % usage for one CPU core after 10 minutes

### ISSUE THREAD

**Issue by hmarthinsen** [autocomplete-python/autocomplete-python#209]
After 10 minutes of inactivity, autocomplete-python kills Python, but this uses up 100 % of one of the CPU cores. autocomplete-python continues to work after this, but the usage stays at 100 % until i close Atom. This is very annoying, since it increases the fan noise and battery usage of the computer. Here is the complete log:

> Window load time: 593ms
> autocomplete-python: Subscribed on event 421.keyup
> autocomplete-python: Subscribed on event 4432.keyup
> /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
> ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
> autocomplete-python: Serializing request to be sent to Jedi Object {id: "8d8b8c3a28adbfb186656767fff59c60", prefix: "value", lookup: "completions", path: "C:\Users\hakonm\Programming\fasad-prototype\fasad\grid.py", source: """"Module for modelling a distribution grid.
> ↵
> ↵Th…the component is consistent."""
> ↵    #     pass
> ↵"…}
> autocomplete-python: Pending requests: 0 Object {}
> autocomplete-python: Spawning python process...
> autocomplete-python: User defined interpreters found Set {"C:\Users\hakonm\WinPython-64bit-3.5.1.3\python-3.5.1.amd64\python.exe"}
> autocomplete-python: Using interpreter C:\Users\hakonm\WinPython-64bit-3.5.1.3\python-3.5.1.amd64\python.exe
> autocomplete-python: Pending requests: 0 Object {}
> autocomplete-python: Deserealizing response from Jedi {"results": [{"type": "variable", "rightLabel": "", "description": "", "text": "value"}, {"type": "builtin", "rightLabel": "", "description": "Inappropriate argument value (of correct type).", "text": "ValueError"}, {"type": "builtin", "rightLabel": "", "description": "vars([object]) -> dictionary\n\nWithout arguments, equivalent to locals().\nWith an argument, equivalent to object.**dict**.", "text": "vars"}], "id": "8d8b8c3a28adbfb186656767fff59c60"}
> 
> autocomplete-python: Got 1 lines
> autocomplete-python: Cached request with ID 8d8b8c3a28adbfb186656767fff59c60
> autocomplete-python: Killing python process after timeout...

**Comment by sadovnychyi** [comment]
Windows?

**Comment by sadovnychyi** [comment]
Related/duplicate #205

**Comment by hmarthinsen** [comment]
Yes, it's on Windows. #205 and #202 are probably related.

**Comment by sadovnychyi** [comment]
Possible fix for huge cpu usage in here #233. If you still have this issue let's continue in #233 or #205.
