### ISSUE TITLE
Is it possible to autocomplete methods of an instance?

### ISSUE THREAD

**Issue by Barrel-Titor** [autocomplete-python/autocomplete-python#227]
I'm a noob and maybe I get something wrong. Please tell me if I make any mistake. Sorry for annoying.
I found sublime can autocomplete methods and variables of an instance but atom cannot(maybe this package enables it but I don't know how to use). Pictures are attached.
<img width="328" alt="atom" src="https://cloud.githubusercontent.com/assets/14011748/17835112/defdd5ec-678e-11e6-9c99-e79882aff2f1.png">
<img width="352" alt="sublime" src="https://cloud.githubusercontent.com/assets/14011748/17835111/ddf96fb2-678e-11e6-8ce8-bce1b1a10f5e.png">

**Comment by sadovnychyi** [comment]
Well it does work for me. Hard to say why it didn't work for you though. 
![image](https://cloud.githubusercontent.com/assets/193864/17887666/171bec26-695a-11e6-8d60-6f65e4b3078b.png)

**Comment by Barrel-Titor** [comment]
I tried it on another computer but it also failed. 
<img width="333" alt="1" src="https://cloud.githubusercontent.com/assets/14011748/17959993/36fbbdfa-6ad6-11e6-8e2d-89524b72879e.png"> 

I find that methods defined in that class can be auto completed while things methods defined outside cannot. :(
![image](https://cloud.githubusercontent.com/assets/14011748/17960099/997d8fbc-6ad6-11e6-8809-b845441f6a09.png)
![image](https://cloud.githubusercontent.com/assets/14011748/17960102/9e378242-6ad6-11e6-86d3-930b4bf2afae.png)

Here's my settings. I think I got something wrong. Would you please have a look at that? Thanks a lot!
![image](https://cloud.githubusercontent.com/assets/14011748/17960272/9a322c96-6ad7-11e6-8437-d7de9a560b12.png)

**Comment by sadovnychyi** [comment]
On your screenshots I can see `accept`, `close`, etc. completed. What do you mean by methods defined outside?

**Comment by Barrel-Titor** [comment]
You see on your screenshot there are methods such as `bind`, `connect`, etc. I find them in the tuple `_socketmethods` outside the class `_socketobject`. Well yours can work well on them but mine cannot. How strange it is :(
![image](https://cloud.githubusercontent.com/assets/14011748/18006307/92c83fc2-6bd1-11e6-8571-ba3d38118f2b.png)

**Comment by sadovnychyi** [comment]
Cannot say why it didn't work for you, but anyway, there's nothing I can do since completions are provided by Jedi. And you are getting at least some of them – so no issues with this package. You can create an issue [here](github.com/davidhalter/jedi).

**Comment by Barrel-Titor** [comment]
All right, I know. Thank you very much!
