### ISSUE TITLE
doesn't have colorful symbol

### ISSUE THREAD

**Issue by DimmuSun** [autocomplete-python/autocomplete-python#231]
I use windows,the plugin seems to do the work partielly,
just have this
![image](https://cloud.githubusercontent.com/assets/21170420/18026508/b01d63c2-6c7b-11e6-939e-61813dab332a.png)

but not this
image
![image](https://cloud.githubusercontent.com/assets/21170420/18026509/b51bd6d8-6c7b-11e6-8d77-4436c9749504.png)

**Comment by DimmuSun** [comment]
it doesn't show color symbol of func ,method,and other ,why?

**Comment by sadovnychyi** [comment]
Because first screenshot is from [autocomplete-snippets](https://atom.io/packages/autocomplete-snippets) (since you are working in an empty file without python grammar – autocomplete-python does not work there). Second one seems like CSS. This package is only for python completions.

**Comment by DimmuSun** [comment]
![image](https://cloud.githubusercontent.com/assets/21170420/18031751/02016c42-6d21-11e6-86b0-3df4b704ca52.png)
![image](https://cloud.githubusercontent.com/assets/21170420/18031755/256f2e12-6d21-11e6-8cd7-93a56a05f0df.png)
I use windows .

**Comment by sadovnychyi** [comment]
Closing this as inactive, please create new issue with full traceback (text, not screenshot please) if you still have any problems.
