### ISSUE TITLE
sh: sysctl: command not found

### ISSUE THREAD

**Issue by mandarup** [autocomplete-python/autocomplete-python#237]
This error keeps popping up

```
autocomplete-python traceback output:
sh: sysctl: command not found
```

**Comment by sadovnychyi** [comment]
If you are using linux I guess it **have** to be there, maybe something is wrong with your OS?

**Comment by mandarup** [comment]
It was with Mac OS. I don't see this error after upgrading to  ```atom >=7.0```

**Comment by drorata** [comment]
I experience this issue as well. I can execute `sysctl` from my console; that is it is installed.

**Comment by drorata** [comment]
I am pointed to something like:

```
module.exports =
  prefix: 'autocomplete-python:'
  debug: (msg...) ->
    if atom.config.get('autocomplete-python.outputDebug')
      return console.debug @prefix, msg...

  warning: (msg...) ->
    return console.warn @prefix, msg...
```

in `/Applications/Atom.app/Contents/Resources/app.asar/static/index.html`
