### ISSUE TITLE
"Autocomplete Function Parameters" wont work if not at the end of the line.

### ISSUE THREAD

**Issue by Olian04** [autocomplete-python/autocomplete-python#238]
This `for i in  range(` will autocomplete into this `for i in  range(start, stop=None, step=1)`.
But this `for i in  range( :` wont autocomplete at all, nor will it provide suggestions such as `stop=None` and `step=1` after typing a comma.

**Comment by sadovnychyi** [comment]
Yeah, it won't automatically insert arguments if there's something after a cursor, `:` in this case. We could whitelist some things there, but usually it's annoying if they are being inserted while you have some code after your cursor.

But I'm still getting completions for arguments like `start`, `stop`, etc.
![image](https://cloud.githubusercontent.com/assets/193864/19233171/793dd40a-8f16-11e6-8ee2-7cc950240701.png)
