### ISSUE TITLE
Where are settings referred to in `Be sure to check package settings and adjust them`

### ISSUE THREAD

**Issue by rkpatel33** [autocomplete-python/autocomplete-python#240]
I am a little confused as to where the settings referred to in the README are (`Be sure to check package settings and adjust them`). In my Atom setting for the `autocomplete-python` package, I don't see anything that  matched this screenshot. Apologies if I am being thick, it's late..:

![image](https://cloud.githubusercontent.com/assets/3799489/19589705/d218003c-973b-11e6-96e0-25336138e0ff.png)

**Comment by sadovnychyi** [comment]
It should be exactly there -- in your Atom settings / packages / autocomplete-python. Maybe you could show your screenshot?

**Comment by rkpatel33** [comment]
Sure, here is what I am seeing:

![image](https://cloud.githubusercontent.com/assets/3799489/19592171/917d9cc8-9748-11e6-9570-ace0900dff60.png)

![image](https://cloud.githubusercontent.com/assets/3799489/19592186/9ea66a24-9748-11e6-8c33-8a7cc85cfdd8.png)

![image](https://cloud.githubusercontent.com/assets/3799489/19592199/af503e5e-9748-11e6-8972-29f53fee1cbc.png)

![image](https://cloud.githubusercontent.com/assets/3799489/19592215/bce5e942-9748-11e6-912a-dfc823fa8a99.png)

![image](https://cloud.githubusercontent.com/assets/3799489/19592230/c8021562-9748-11e6-8be7-1643b53c07cf.png)

**Comment by rkpatel33** [comment]
I just uninstalled then reinstalled and now the settings are there. Some weird bug I guess. I thought I had done that, but may the issue was that I was messing around with another package that disabled this one and it didn't get re-enabled properly.  Sorry about that, thanks for getting back.

**Comment by sadovnychyi** [comment]
Glad it works now!

**Comment by sadovnychyi** [comment]
It should be exactly there -- in your Atom settings / packages /
autocomplete-python. Maybe you could show your screenshot?
