### ISSUE TITLE
Do not apply completion when pressing enter?

### ISSUE THREAD

**Issue by yxlao** [autocomplete-python/autocomplete-python#243]
The default behavior allows applying autocomplete using either <kbd>tab</kbd> or <kbd>enter</kbd>. Is there a way to not apply completion when pressing <kbd>enter</kbd>?

**Comment by sadovnychyi** [comment]
Not sure, check autocomplete-plus settings.

**Comment by yxlao** [comment]
thanks! autocomplete-plus settings solve the problem.
