### ISSUE TITLE
Autocomplete-python removes (overrides) some of the built-in snippets

### ISSUE THREAD

**Issue by pingshunhuangalex** [autocomplete-python/autocomplete-python#245]
Use `class` as an example:
When autocomplete-python is not installed:
![image](https://cloud.githubusercontent.com/assets/17170199/19991414/34c6f94c-a289-11e6-961d-c74aa9e55ba6.png)
![image](https://cloud.githubusercontent.com/assets/17170199/19991423/3dcf2b4a-a289-11e6-8ecf-6f01fe749ea2.png)

When autocomplete-python is installed:
![image](https://cloud.githubusercontent.com/assets/17170199/19991398/08e01d36-a289-11e6-8bde-a744d9ed3ce7.png)
![image](https://cloud.githubusercontent.com/assets/17170199/19991430/58cd0502-a289-11e6-8192-8a31d520e6b3.png)

Same things happen to other snippets too (e.g. `def`) wherever there is a conflict on name...

**Comment by sadovnychyi** [comment]
There's an option for this:

![image](https://cloud.githubusercontent.com/assets/193864/20001098/a2449610-a2b5-11e6-8a00-2884d97ef81b.png)

Set it to 1 and restart the editor.
