### ISSUE TITLE
Hyperclick doesn't work in autocomplete-python

### ISSUE THREAD

**Issue by pingshunhuangalex** [autocomplete-python/autocomplete-python#246]
I wanted to provide more info, but there is no error messages. Hyperclick just won't work in autocomplete-python.

It works for my js, so it's not Hyperclick's problem. The autocomplete part works fine, so i don't think it's the installation or the config problem either.

Any help would be appreciated. Thanks.

**Comment by pingshunhuangalex** [comment]
I found the reason, I'm using `Python Django` instead of `Python` as the file type, is it possible for you to add in this file type, so it can be recognised by Hyperclick? Thanks.

**Comment by pingshunhuangalex** [comment]
Thank you so much @sadovnychyi 
That was very responsive, efficient, and precise.

**Comment by sadovnychyi** [comment]
I didn't even say anything 😄
