### ISSUE TITLE
'Welcome to Kite' page doesn't mention it's from this plugin

### ISSUE THREAD

**Issue by underyx** [autocomplete-python/autocomplete-python#256]
I was utterly confused about how it got in my Atom until I clicked 'learn more' link at the end.

**Comment by lutzhorn** [comment]
+1 Please make it clear *why* Atom suddenly askes to create a Kite account. Uploading all my code to some 3rd party side is the last thing I will do.

**Comment by dhung09** [comment]
Hi @underyx and @lutzhorn - When we designed the installation process for autocomplete-python, we thought it would be clear to the users how to opt-out of using Kite and instead use the legacy autocomplete engine. Clearly we were wrong. Was there anything in particular about the install flow that was confusing or misleading to you?

With regards to uploading code, we realize that users are (and rightfully should be) sensitive to storing their code on the cloud. We take privacy and security very seriously and you can read our policy [here](https://kite.com/privacy/) and more on how we think about the tradeoffs [here](https://kite.com/blog/). In either case, if you don't want to use Kite anymore after installing it, you can remove it from your computer via the following steps:

1. Disable Kite in the autcomplete-python plugin settings within Atom. It should be the first checkbox.
2. Remove the Kite plugin from Atom
3. Remove `/Applications/Kite.app`
4. If you believe your code has been uploaded already and would like for us to delete it, feel free to shoot us an email at securitycontrols@kite.com and we'd be happy to remove it for you.

**Comment by underyx** [comment]
@dhung09 I myself have no privacy concerns, and do not want to opt-out of using Kite.

My problem was: I've been an autocomplete-python user for a long long while, and must have updated it a few days ago to a version that includes the Kite prompt. When I started up Atom after a restart a few days later, this Kite prompt appeared out of the blue, with no explanation as to why it would be there. This is my only issue, as also described by the issue title:

>'Welcome to Kite' page doesn't mention it's from this plugin

Adding just a note at the start that the message is from the autocomplete-python plugin would be a sufficient fix.

**Comment by dhung09** [comment]
Ok got it. I can definitely see how that would be confusing. Thanks for clarifying this and I'll work on a fix for this issue

**Comment by lutzhorn** [comment]
@dhung09 For a start you should design the process to be opt-in, not opt-out.

Why do you think the Jedi engine is 'legacy'?

**Comment by dhung09** [comment]
> For a start you should design the process to be opt-in, not opt-out.

The process is supposed to be opt-in. In addition to asking the user to explicitly enable Kite on the first step of the install process, the default behavior if you were to close the installation page is to keep using the Jedi engine without Kite. @lutzhorn sorry if you were confused by this - Is there anything we could have done to make it more clear?

> Why do you think the Jedi engine is 'legacy'?

Poor choice of words on my part. What I meant was the Jedi engine was the predecessor to Kite, though the plugin will continue to support whatever choice the user wants. Hope this clarifies!

**Comment by aklaver** [comment]
Disconcerting to see 'Use Kite-powered Completions' checked when I never got a prompt for its use during the update process. Now I am on Linux so it seems to go nowhere and do nothing at the moment. Still, not pleased that a company is potentially going to suck up my code for its benefit. The Kite thing should be an entirely separate plugin/process that a user has to find and download on their own. Not really interested in making these folks:

"Our investors include SV Angel, founders from Dropbox, Paypal, Palantir, Quora, and WordPress, amongst other amazing investors."

more money.

**Comment by underyx** [comment]
@aklaver I think you accidentally commented on the wrong issue?

**Comment by evanroane** [comment]
After the experience of trying to grab my email and get access to my user dir, I uninstalled this package

**Comment by underyx** [comment]
@evanroane Same goes for you. I'd suggest that you create a new issue, since this one is unrelated.

**Comment by lutzhorn** [comment]
The previous comments are very related. autocomplete-python should get rid of Kite.
