### ISSUE TITLE
Question: How to write documentation for a function

### ISSUE THREAD

**Issue by Guy-Markman** [autocomplete-python/autocomplete-python#266]
Until now I wrote the documentation for every function in a comment above them.
How do I need to write the documentation so It'll show in your autocomplete?

**Comment by sadovnychyi** [comment]
Use doc strings, that's the only way to write docs in python.

E.g. 

```python
def hello():
  """Output hello world.
  """
  print('hello world')
```

See https://www.python.org/dev/peps/pep-0257/

**Comment by Guy-Markman** [comment]
Thank you
