### ISSUE TITLE
Failed to load the autocomplete-python package

### ISSUE THREAD

**Issue by KangGrandesty** [autocomplete-python/autocomplete-python#267]
##  I moved the package files into `.atom\packages\`,but, when I restarted atom, it noticed `Failed to load the autocomplete-python package`

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**:  Windows 10
**Thrown From**: [autocomplete-python](https://github.com/autocomplete-python/autocomplete-python) package, v1.8.26

### Stack Trace

Failed to load the autocomplete-python package

```
At '../node_modules/kite-installer/styles/styles.less' wasn't found in C:\Users\kang\.atom\packages\autocomplete-python-1.8.26\styles\autocomplete-python.less:2:0

LessError: '../node_modules/kite-installer/styles/styles.less' wasn't found
  at C:\Users\kang\.atom\packages\autocomplete-python-1.8.26\styles\autocomplete-python.less:2:0
```

**Comment by sadovnychyi** [comment]
Why not just use usual installer? Run apm install from package dir if you
did it manually.

**Comment by adammenges** [comment]
this even happens if you sync packages across machines, which works fine for all of my other installed packages

also only complains about Kite, even though it's not it use, seems like if I'm not using Kite it shouldn't matter

**Comment by zhangliu1988** [comment]
usual installer is also can net be used.

**Comment by plmsmile** [comment]
I am having the same problem. How did you solve it?

**Comment by sadovnychyi** [comment]
`apm install` from package directory could help, or completely uninstall and install it again. This happens because dependencies weren't installed properly.

**Comment by niclonious** [comment]
Had the same issue, reinstalling the package from Atom UI helped.
