### ISSUE TITLE
autocomplete not working only on cv2 package

### ISSUE THREAD

**Issue by clickilan** [autocomplete-python/autocomplete-python#268]
new user.

autocomplete-python works great for me on internal modules as well as site-specific excluding one package: cv2 (opencv). i tried opencv 3.1 and 3.2 stable and the same problem happens with both:

if i try to autocomplete another package like matplotlib, everything works fine:

![image](https://cloud.githubusercontent.com/assets/24826144/21849795/44f06274-d810-11e6-8285-1ba3e3db995f.png)

> autocomplete-python: Using cached response with ID bb7c74d9891aebaf8a28fef99f7818f3
11log.coffee:5 autocomplete-python: Using cached response with ID 1411ccf1f139bf6bf2ce6db590232252
log.coffee:5 autocomplete-python: Using cached response with ID 2a7b28de156ec2950ec5c55dfef1ea1f
log.coffee:5 autocomplete-python: Trying to complete arguments on keyup event KeyboardEvent {isTrusted: true, key: "(", code: "Digit9", location: 0, ctrlKey: false…}
log.coffee:5 autocomplete-python: Serializing request to be sent to Jedi Object {id: "d729410aa2fa8779ffeb461667df66a6", lookup: "arguments", path: "C:\Users\ilangut\Dropbox\python\object_track\the_bot.py", source: "#!/usr/bin/python3↵import numpy as np↵import matpl…     break↵cap.release()↵cv2.destroyAllWindows()↵", line: 4…}
log.coffee:5 autocomplete-python: Pending requests: 0 Object {}
log.coffee:5 autocomplete-python: Deserealizing response from Jedi {"arguments": "${1:x}, ${2:y}, ${3:dx}, ${4:dy}$0", "id": "d729410aa2fa8779ffeb461667df66a6", "results": []}
log.coffee:5 autocomplete-python: Got 1 lines
log.coffee:5 autocomplete-python: Removing old item from cache with ID b9eda6e0ddcc03fd7d4697899947f39e
log.coffee:5 autocomplete-python: Cached request with ID d729410aa2fa8779ffeb461667df66a6

when i try to autocomplete cv2 it just does not work with no errors:

![image](https://cloud.githubusercontent.com/assets/24826144/21850160/e4f5f18e-d811-11e6-8f63-82f72b97eb02.png)

>autocomplete-python: Using cached response with ID 11ee59ccf71e204aa3fdbd10eb00e1a7
3log.coffee:5 autocomplete-python: Using cached response with ID cbc61569245ef68e3146dd63d92c558d
log.coffee:5 autocomplete-python: Using cached response with ID 462d260919fb1e97994f657328cbc6ed

any ideas?

**Comment by sadovnychyi** [comment]
Thanks for good quality issue with all the details!

It's most likely that Jedi does not support python libraries written in C, like opencv.

You can track it here: https://github.com/davidhalter/jedi/issues/777

**Comment by clickilan** [comment]
Thanks for the rapid answer.

any change Windows or Linux getting kite support?

**Comment by sadovnychyi** [comment]
Cannot answer any of your questions, sorry!

Closing this since there's nothing I can do.

**Comment by lhelontra** [comment]
Was fixed with jedi 0.11.0.
