### ISSUE TITLE
Autocomplete-python insertion breaks swallowing of quotation marks inserted by bracket-matcher

### ISSUE THREAD

**Issue by FHeilmann** [autocomplete-python/autocomplete-python#271]
### Prerequisites

debug log here : http://pastebin.com/TZZ7MJrs

installed packages, **however I disabled all of them except for autocomplete-python:**

MagicPython@1.0.3
atom-clock@0.1.2
**autocomplete-python@1.8.26**
git-plus@7.1.0
highlight-selected@0.12.0
hyperclick@0.0.39
language-latex@1.0.0
latex@0.42.1
latexer@0.3.0
latextools@0.8.5
linter@1.11.21
linter-chktex@1.3.0
merge-conflicts@1.4.4
minimap@4.26.6
minimap-git-diff@4.3.1
minimap-highlight-selected@4.5.0
pdf-view@0.54.0
preview-inline@1.4.5
project-manager@3.3.3
python-tools@0.6.9
script@3.14.0
svn@0.0.13

bracket-matcher version 0.85.1

I encountered this problem with both `language-python 0.45.1` and `MagicPython 1.0.3`

atom version 1.13.0-1\~webupd8\~1 from the webupd8 ppa

German QWERTZ keyboard layout.

### Steps to Reproduce

1. Have both `autocomplete-python` and `bracket-matcher` enabled
2. Have the "Autocomplete Brackets" setting active in `bracket-matcher`
3. Create a new .py file to activate autocomplete-python
4. Type the following keystrokes:  `print("Test")

**Expected behavior:** [What you expected to happen]

Buffer shows `print("Test")`

**Actual behavior:** [What actually happened]

Buffer shows `print("Test")")`

It seems like the automatic insertion of the "value" string when typing the opening bracket breaks the swallowing of the quotation marks by `bracket-matcher`. This problem does **not** show when typing

`print(Test)`

I am not sure if this is a bug with bracket-matcher or autocomplete-python but I thought I'd try this repo first.

Bests,

Florian

**Comment by sadovnychyi** [comment]
Can you reproduce it with `Autocomplete function parameters` setting set to `none`?

This is expected behaviour from my machine:

Autocomplete function parameters: All
![sample](https://cloud.githubusercontent.com/assets/193864/21924032/348ed2f0-d9b2-11e6-9b1d-40290932d57f.gif)

Autocomplete function parameters: Required
![sample](https://cloud.githubusercontent.com/assets/193864/21924057/4e80f652-d9b2-11e6-96e0-3f87cf7e41b2.gif)

**Comment by FHeilmann** [comment]
`None` **Does not** produce the error
`All` **Does** produce the error (i end up with 
`print("Test"", sep=' ', end='n', file=sys.stdout, flush=False)`
when typing
`print(Test"`)

The important step is when you try to close the quotation marks after the "value" bit has been inserted. bracket-matcher should swallow the closing quotation marks since they were inserted by it, but it doesn't

**Comment by sadovnychyi** [comment]
Ok, I see it.

You actually have to type `print("test")` despite of what is on the screen.

Unfortunately I cannot think about any fix for this, at least for now. Arguments completion on specific keystroke is already a "hack" – maybe it should be done in another way.

For now your only option is to disable argument completion.

**Comment by FHeilmann** [comment]
Sorry I misclicked

**Comment by FHeilmann** [comment]
Sorry I misclicked

**Comment by FHeilmann** [comment]
For completeness sake, here's a gif showing the issue. It doesn't happen for "print" anymore since the "value" arg is not inserted anymore.

![issue](https://cloud.githubusercontent.com/assets/4352664/22879739/aa7a80a0-f1df-11e6-8554-d208c70b46b1.gif)

**Comment by FHeilmann** [comment]
I know this is basically dead, but apparently, the correct "usage" of this is that you have to "tab" out of the quotation marks instead of typing them out
