### ISSUE TITLE
Function.extractParams is deprecated.

### ISSUE THREAD

**Issue by yzinets** [autocomplete-python/autocomplete-python#272]
Assigning custom properties to a marker when creating/copying it is
deprecated. Please, consider storing the custom properties you need in
some other object in your package, keyed by the marker's id property.
```
Function.extractParams (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:43:14)
MarkerLayer.markRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:196:71)
DisplayMarkerLayer.markBufferRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:90:62)
TextEditor.markBufferRange (/usr/share/atom/resources/app.asar/src/text-editor.js:1753:38)
constructor._showSignatureOverlay (/home/cornel/.atom/packages/autocomplete-python/lib/provider.coffee:294:23)
<unknown> (/home/cornel/.atom/packages/autocomplete-python/lib/provider.coffee:346:28)
```

**Comment by sadovnychyi** [comment]
https://github.com/autocomplete-python/autocomplete-python/issues/269

**Comment by tjgerot** [comment]
Still getting warnings from Deprecation Cop regarding this.

Assigning custom properties to a marker when creating/copying it is deprecated. Please, consider storing the custom properties you need in some other object in your package, keyed by the marker's id property.

```
Function.extractParams - C:\Users\XXX\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\text-buffer\lib\marker.js:43:14
MarkerLayer.markRange - C:\Users\XXX\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:215:71
DisplayMarkerLayer.markBufferRange - C:\Users\XXX\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\text-buffer\lib\display-marker-layer.js:105:52
TextEditor.markBufferRange - C:\Users\XXX\AppData\Local\atom\app-1.16.0\resources\app.asar\src\text-editor.js:1781:38
constructor._showSignatureOverlay - C:\Users\XXX\.atom\packages\autocomplete-python\lib\provider.coffee:294:23
<unknown> - C:\Users\XXX\.atom\packages\autocomplete-python\lib\provider.coffee:346:28
```

All my packages are up to date.

**Comment by billgertz** [comment]
Still getting the same deprecation notice, all packages up to date as well. What can we send to help debug?
![screen shot 2017-05-31 at 11 37 47](https://cloud.githubusercontent.com/assets/3613249/26625913/d83a23dc-45f5-11e7-85fa-c010ceff803c.png)

**Comment by madLyfe** [comment]
me as well:

Assigning custom properties to a marker when creating/copying it is deprecated. Please, consider storing the custom properties you need in some other object in your package, keyed by the marker's id property.

Function.extractParams - <embedded>:110800:20
MarkerLayer.markRange - <embedded>:71792:77
DisplayMarkerLayer.markBufferRange - <embedded>:111413:58
TextEditor.markBufferRange - <embedded>:4019:44
constructor._showSignatureOverlay - C:\Users\madLy\.atom\packages\autocomplete-python\lib\provider.coffee:294:23
<unknown> - C:\Users\madLy\.atom\packages\autocomplete-python\lib\provider.coffee:346:28
