### ISSUE TITLE
Underscore key causing strange behavior

### ISSUE THREAD

**Issue by neurovertex** [autocomplete-python/autocomplete-python#274]
There's a bug when typing the underscore key, I've only seen it happen inside strings so far. My non-US (AZERTY) keyboard layout could have something to do with this.

1. Create a python file (duh)
2. Declare something auto-completable, like a variable or a function
3. Write the name of the latter in a string
4. At the end of the name, inside the string, press underscore

**Expected behavior:**
Adds an underscore at the end of the string.

**Actual behavior:**
The underscore appears when the key is pressed, then immediately disappears when the key is released.

![Animated demonstration](https://neurovertex.eu/upload/autocompletePythonIssue.gif)

**Comment by sadovnychyi** [comment]
Yep, definitely related to your layout.

See https://github.com/autocomplete-python/autocomplete-python/blob/master/lib/provider.coffee#L272-L280.

As I remember there's new keyboard events API in Atom, probably we should try to use it.

**Comment by sadovnychyi** [comment]
Please check it in v1.8.27 and let me know if it's fixed.

**Comment by neurovertex** [comment]
Seems to work fine now. Thanks for the quick fix 👍
