### ISSUE TITLE
autocomplete-python throws BASH_FUNC_module import warning

### ISSUE THREAD

**Issue by DanBuchan** [autocomplete-python/autocomplete-python#275]
On centos 7 with Atom 1.13.0x64 the following warning is thrown when autocomplete-python first attempts to autocomplete. All subsequent autocomplete events do not throw this error.

### Steps to Reproduce

1. Install autocomplete-python
2. Close Atom
3. Open Atom
4. Open python file
5. Start typing something that might trigger autocomplete

**Expected behavior:**
autocomplete dialogue appears, no warnings are thrown

**Actual behavior:**
no dialogue appears the following warning is thrown:

autocomplete-python traceback output:
/bin/sh: module: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_module'
This erroneous behaviour does not occur for all subsequent autocomplete events. Only the first event when newly opening Atom

**Comment by shermdog** [comment]
Similar behavior with Atom version 1.13.1 on Fedora 25

```
sh: module: line 1: syntax error: unexpected end of file
sh: error importing function definition for `BASH_FUNC_module'
sh: scl: line 1: syntax error: unexpected end of file
sh: error importing function definition for `BASH_FUNC_scl'
```

**Comment by sadovnychyi** [comment]
Seems like it's not related to this package.

See https://github.com/AtomLinter/linter-flake8/issues/165 and let me know if it's works for you so we can close this.

**Comment by DanBuchan** [comment]
Ok. I have followed that link (and others) and tried the following

1) uninstall scl-utils and reboot
2) ensure my .bashrc is syntax correct
3) Add semicolons to the end of every line in my .bashrc

None of these suggestions/solutions from around the internet worked. Neither do I have flake8 installed.

I have however tracked this down to how the atom rpm installs atom for fedora/centos after running
```
rpm -Uvh atom.x84_64.rpm
```
I can now find 2 copies of the atom executable one at `/bin/atom` and one at `/usr/share/atom/atom`. I would typically expect one of those to be a symlink to the other but that is not the case here. The desktop icon that Atom adds to gnome is pointed at the executable `/usr/share/atom/atom `

If I run atom from the command line with `/usr/share/atom/atom` I get the following error
```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```
and the `BASH_FUNC_module` error for autocomplete-python persists. And you see this same behaviour with the desktop icon

If I run atom with /bin/atom there are no errors and everything works as expected.

### Current Solutions

Either

1. Always run atom from the commandline allowing it to resolve to `/bin/atom`
2. As I'm using gnome I changed the atom desktop icon to always call `/bin/atom` is called. I made the following edits to `/usr/share/applications/atom.desktop`
```
Exec=/bin/atom %F
Icon=/usr/share/atom/atom.png
```

**Comment by sadovnychyi** [comment]
Thanks for investigation! There's nothing I can do unfortunately.

Some atom-related issues as well:
https://github.com/AtomLinter/linter-puppet-lint/issues/68
https://github.com/atom/atom/issues/13451

**Comment by DanBuchan** [comment]
Yeah this is obviously not an issue with autocomplete and with how Atom builds its rpm. I'll close this issue here and raise it with them

**Comment by TJProgrammer** [comment]
Only a simple question: why Atom can't repair this problem if the solution is a one line change in rpm build?
https://github.com/platformio/platformio-atom-ide-terminal/issues/120#issuecomment-274870224

**Comment by sadovnychyi** [comment]
@TJProgrammer No way I can answer this, you should track Atom issue [here](https://github.com/atom/atom/issues/13733).

**Comment by haghighi-ahmad** [comment]
@shermdog 
I'm using **virtualenv** and I got the same error when opening Atom in normal/usual way.
To solve problem:

- Active virtualenv in Terminal, and then launch Atom from terminal for your project directory
e.g.  (suppose you are in virtualenv's directory)
```
$ source bin/activate
$ atom project01
```
OR

- Install **atom-python-virtualenv** package for Atom
 ([https://atom.io/packages/atom-python-virtualenv](https://atom.io/packages/atom-python-virtualenv))
