### ISSUE TITLE
Expose $HOME as a variable for use in virtualenv paths

### ISSUE THREAD

**Issue by jrial** [autocomplete-python/autocomplete-python#283]
I see there's a $PROJECT and $PROJECT_NAME, but in the example the path to a virtualenvwrapper-managed venv starts with "/Users/name/". In the UNIX shell, you can get that with $HOME.

It would be nice if this became a valid variable in path names as well. It's a minor thing, but it would allow for more portability of configs between machines.

An example I can think of is a developer who wants the same Atom configuration at work and at home, but whose professional and personal usernames don't match. Or a prepared Atom config that new employees can download into their home folders when joining the company.

**Comment by sadovnychyi** [comment]
Can you confirm that `~/` does not work?

**Comment by sadovnychyi** [comment]
Closing this since you are most likely able to use `~` as a shortcut to your home dir.

**Comment by jrial** [comment]
Seems to work indeed. Tx for the suggestion. The thought of using `~` hadn't even crossed my mind.
