### ISSUE TITLE
Plugin style breaks atom's layout

### ISSUE THREAD

**Issue by mtorromeo** [autocomplete-python/autocomplete-python#288]
When autocomplete-python is installed it imports the `kite-installer/styles/styles.less` stylesheet which contains rules that break atom's layout.

I noticed issues in atom's Packages page but there are probably issues elsewhere.

With plugin enabled:
![enabled](https://cloud.githubusercontent.com/assets/51503/22968601/4f4ec37a-f36b-11e6-97c5-77e93fc77ee4.png)

With plugin disabled:
![disabled](https://cloud.githubusercontent.com/assets/51503/22968608/5ab221ee-f36b-11e6-9e56-d45a91f9d477.png)

**Comment by sadovnychyi** [comment]
Should be fixed with next release.
