### ISSUE TITLE
Getting an error everytime I type

### ISSUE THREAD

**Issue by Ryunaq** [autocomplete-python/autocomplete-python#297]
I keep getting this error whenever I type even a single letter: 

![image](http://image.prntscr.com/image/769c2faa593e48fa85cc598a86b513b2.png)

I'm new in this kind of stuff so I don't really know what that means. 

I think my configuration is alright, but again, I don't really know about this stuff, here is my executable path just in case. 
![image](http://image.prntscr.com/image/4157ecd3c3044e5dacdbe9159c5ec513.png)

Thanks.

**Comment by sadovnychyi** [comment]
You should look for a way to enable dev/null on your machine.

See https://github.com/ipython/ipython/issues/9023.
