### ISSUE TITLE
Autocomplete not working for imported modules in venv

### ISSUE THREAD

**Issue by sh3lld00m** [autocomplete-python/autocomplete-python#298]
### Steps to Reproduce

1. Create and enable Python 2.7 virtual environment using virtualenv: located in venv folder inside the project folder.
```
bqCodelab (venv)$ pwd
/Users/javiercm/Code/Projects/bqCodelab
bqCodelab (venv)$ tree -d -L 2
.
└── venv
    ├── bin
    ├── include
    └── lib
bqCodelab (venv)$ echo $VIRTUAL_ENV
/Users/javiercm/Code/Projects/bqCodelab/venv
bqCodelab (venv)$ which python
/Users/javiercm/Code/Projects/bqCodelab/venv/bin/pip2
bqCodelab (venv)$ which pip2
/Users/javiercm/Code/Projects/bqCodelab/venv/bin/pip2
```
2. Install module using pip2:
```
bqCodelab (venv)$ pip2 install --upgrade google.cloud 
bqCodelab (venv)$ pip2 show google.cloud
Name: google-cloud
Version: 0.23.0
Summary: API Client library for Google Cloud
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google Cloud Platform
Author-email: jjg+google-cloud-python@google.com
License: Apache 2.0
Location: /Users/javiercm/Code/Projects/bqCodelab/venv/lib/python2.7/site-packages
Requires: google-cloud-storage, google-cloud-core, google-cloud-vision, google-cloud-translate, google-cloud-bigtable, google-cloud-pubsub, google-cloud-dns, google-cloud-error-reporting, google-cloud-speech, google-cloud-monitoring, google-cloud-resource-manager, google-cloud-datastore, google-cloud-spanner, google-cloud-language, google-cloud-logging, google-cloud-runtimeconfig, google-cloud-bigquery
``` 
3. Open Atom from the project folder
```
bqCodelab (venv)$ atom .
```
**Expected behavior:**
To get autocompletion and access to google.cloud module classes and submodules inside Atom.

**Actual behavior:**
Autocomplete does work for standard Python modules, but it does not detect the previously installed module:
<img width="347" alt="screen shot 2017-03-23 at 9 38 33 am" src="https://cloud.githubusercontent.com/assets/2262266/24244980/fd4f0f20-0fb8-11e7-8313-86ee850f34b4.png">
nor it does autocompletes once the module has been imported:
<img width="306" alt="screen shot 2017-03-23 at 11 10 38 am" src="https://cloud.githubusercontent.com/assets/2262266/24245121/78a364a0-0fb9-11e7-8e1f-3bb5277cb72c.png">

The extension does not throw any error in Developers console. I've also tried adding both Python Executable Paths (/Users/javiercm/Code/Projects/bqCodelab/venv/bin/python) and Extra Paths for Packages (/Users/javiercm/Code/Projects/bqCodelab/venv/lib/python2.7/site-packages) without success.

**Comment by sadovnychyi** [comment]
I'm pretty sure it's going to work for most of modules installed in venv with google cloud as an exception.

I did try to install it with this steps:
1. `cd my/project && env/bin/pip install google.cloud`
2. Try `from google.` completions – I'm only seeing my app engine related completions – removing `/usr/local/google_appengine` from `Extra Paths For Packages` helps to eliminate them.
3. Still cannot see `google.cloud` module – by going into `env/lib/python2.7/site-packages/google` I can see that there's no `__init__.py` file presented in both root and `cloud` sub-package. I've created them and now I can see them in Atom.

![image](https://cloud.githubusercontent.com/assets/193864/24287967/9a4923bc-10b6-11e7-877e-e4ca40d7a4b7.png)

So, I see no issues with this package. I'm sure other modules are going to work for you.
I cannot answer why `__init__.py` files are not there and how is it possible to work without them at all. The whole `google` package seems super confusing for me especially if you use app engine standard environment – in this case it seems it's not possible to use them together at all.

**Comment by sh3lld00m** [comment]
Looks the reason why the package has no `__init__.py` is because the package creators switched to [Namespace Packages](https://www.python.org/dev/peps/pep-0420/): see [Missing __init__.py #2767](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2767) in GitHub. I guess packages following it should have the same issue.

I've seen PyCharm CE is performing autocompletion for this package, but I've got no idea how they do it without the `__init__.py` file.

**Comment by sadovnychyi** [comment]
Possibly worth to fill a bug in Jedi.

https://github.com/davidhalter/jedi

**Comment by sadovnychyi** [comment]
https://github.com/davidhalter/jedi/issues/122
