### ISSUE TITLE
confirming suggestion just one char long

### ISSUE THREAD

**Issue by Minasodrom** [autocomplete-python/autocomplete-python#300]
When you have defined a variable name with the lenght of one character (eg. x) and and later try to use it (confirm its suggestion with enter or tab), the suggestion window doesnt go away.
this doesnt happen for [. (], only for [a-zA-Z_] when the suggestion is also only one char long.

i use a clean atom install with only autocomplete-python installed on windows 10
thank you

**Comment by sadovnychyi** [comment]
I can see the same behaviour in another autocomplete-plus providers as well, .e.g go-plus – so it's not an issue with this package.

You could turn off completions for single letter words by changing `Regex To Trigger Autocompletions` setting to something like `([. (]|[a-zA-Z_][a-zA-Z0-9_]{2,})`.
