### ISSUE TITLE
Using “TAB” instead “ENTER” for auto completion

### ISSUE THREAD

**Issue by xshrim** [autocomplete-python/autocomplete-python#303]
I love autocomplete-python, but that it selects the first match when i hit enter key is a bit annoying. I just want to jump to a new line usually, not autocomplete. 
So, is it possible that allows user to  configure the key for using 'TAB' instead “ENTER” for auto completion?
Thanks.

**Comment by sadovnychyi** [comment]
You can configure this in autocomplete-plus settings:
![image](https://cloud.githubusercontent.com/assets/193864/25304319/9bfb436e-2797-11e7-8390-5cf074a5ae16.png)
