### ISSUE TITLE
CPU intensive python process sometimes launched when atom is closed if this package is installed

### ISSUE THREAD

**Issue by jjmark15** [autocomplete-python/autocomplete-python#310]
When atom is closed after using autocomplete, a python process launches in the background. This process is CPU intensive and doesn't end, has to be force closed. I am using the Jedi system on Windows 10.

I've been using this as a workaround:

import psutil
from time import sleep

PROCNAME = "python.exe"

for proc in psutil.process_iter():
    # check whether the process name matches
    if proc.name() == PROCNAME and proc.cpu_percent(interval=0.2) > 20:
        cpu = proc.cpu_percent(interval=0.2)
        proc.kill()
        print(proc.name(), 'stopped ({}%)'.format(cpu))
        break
sleep(1)

**Comment by warmar** [comment]
+1. This bug has been causing me a lot of problems. FYI I am on Windows 10.

**Comment by rlam3** [comment]
+1

**Comment by vuki** [comment]
Same problem, Windows 10. Atom was closed hours ago and suddenly I hear fan spinning in my laptop. I'm checking running processes - completion.py from autocomplete-python, 25% of CPU usage. Please fix this.

**Comment by KappaLambda** [comment]
+1  
After closing Atom, there is a Python process with a CPU usage of 15-20%. This makes my PC really slow. Even performing simple tasks, PC lags. The process never stops unless I manually stop it. Reappears when I open again Atom.
The process is there while working with atom but has no CPU usage(0%). Goes to mentioned usage after exiting atom.
I am on Windows 10 Creator's Edition.

**Comment by rlam3** [comment]
+1000

**Comment by Anuj2976** [comment]
+1

**Comment by hodossy** [comment]
+1
For me closing Atom is not even necessary, however I could not figure out what is triggering the high load.
I am on Windows 10 too.

**Comment by Cortajarena** [comment]
+1
Same here

**Comment by christophra** [comment]
+1
Atom    : 1.13.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by rlam3** [comment]
@sadovnychyi We totally love this atom package. But as a community would love your feedback on this. Thanks!

**Comment by christophra** [comment]
How does it work, do I report a separate issue for Linux?

**Comment by sadovnychyi** [comment]
It's ok to have this issue for both windows and Linux. But I never seen
this issue on macos. Will try to reproduce it on windows.

**Comment by mattb5906** [comment]
Also having problems with this, but only on one of my machines. Closing causes the python shell to go into a high CPU state with Atom owning the process and failing to close.

On some occasions the shell process has become detached from Atom and starts running as a parent process when viewed in the Windows Task Manager.

Python 3.6.4, Windows 10 1709

**Comment by micahjsmith** [comment]
experiencing this as well on python 3.6, macos 10.13.4, atom 1.26.1, autocomplete-python 1.10.5

even after closing atom, a python3.6 process spawned by autocomplete-python continues to use 100% cpu.

thanks!

**Comment by mattb5906** [comment]
Video of the issue:
https://drive.google.com/file/d/1ll1MIs8MLQuXuTgtUGneFUuwj8FIGfJ3/view

**Comment by BigIskander** [comment]
I just edited the file autocompletion.py
Changed this text:
    def watch(self):
        while True:
            try:
                sys.stdout, sys.stderr = self.devnull, self.devnull
                self._process_request(self._input.readline())
            except Exception:
                ys.stderr = self.stderr
                sys.stderr.write(traceback.format_exc() + '\n')
                sys.stderr.flush()
                
to, this: 
    def watch(self):
        while True:
            try:
                sys.stdout, sys.stderr = self.devnull, self.devnull
                self._process_request(self._input.readline())
            except Exception:
                #sys.stderr = self.stderr
                #sys.stderr.write(traceback.format_exc() + '\n')
                #sys.stderr.flush()
                sys.exit(1)

**Comment by segevfiner** [comment]
See https://github.com/brennv/autocomplete-python-jedi/pull/21

**Comment by brgsstm** [comment]
+1 Windows 10 and autocomplete-python
