### ISSUE TITLE
autocomplete can't complete gobject(python3 gtk)

### ISSUE THREAD

**Issue by Sherlock-Holo** [autocomplete-python/autocomplete-python#315]
### Prerequisites

* [ ] Please make sure to properly [configure](https://github.com/autocomplete-python/autocomplete-python#configuration) plugin first if you simply cannot see any completions.
* [ ] It's always helpful if you include debug logs with your issue:
  * Go to package settings to enable them
  ![image](https://cloud.githubusercontent.com/assets/193864/19852051/01e4e45c-9f9c-11e6-9480-dd22147c82b3.png)
  * Open `dev tools` using command palette and you should see some `autocomplete-python` records in console tab. This will include parts of your code – make sure to remove everything you don't want to share.

### Steps to Reproduce

1. [First Step]
```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
```
2. [Second Step]
wait for complete 'Gtk'

**Expected behavior: it completes 'Gtk' and then i can type 'Gtk.' and shows me likes 'Gtk.window'

**Actual behavior: nothing happened, i can't see any complete

**Comment by sadovnychyi** [comment]
That's an issue with Jedi and you could try to switch to another completion provider (Kite), which is likely to work with such libraries.

You can track the progress of Jedi's issue [here](https://github.com/davidhalter/jedi/issues/531).
