### ISSUE TITLE
Executable Path

### ISSUE THREAD

**Issue by diazgilberto** [autocomplete-python/autocomplete-python#317]
### Prerequisites

* [ ] Please make sure to properly [configure](https://github.com/autocomplete-python/autocomplete-python#configuration) plugin first if you simply cannot see any completions.
* [ ] It's always helpful if you include debug logs with your issue:
  * Go to package settings to enable them
  ![image](https://cloud.githubusercontent.com/assets/193864/19852051/01e4e45c-9f9c-11e6-9480-dd22147c82b3.png)
  * Open `dev tools` using command palette and you should see some `autocomplete-python` records in console tab. This will include parts of your code – make sure to remove everything you don't want to share.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

This is more of a question. I would like to know what is the precedence of path for the Executable Path. If I set the following...

    ./bin/python;/.pyenv/shims/python

Which one are you going to use first and which one is the fall back and how it works for the packages?

Thank you!!

**Comment by sadovnychyi** [comment]
First one is going to be used first, then fall back on second one if first
is missing, and so on.

**Comment by scriptBoris** [comment]
Sorry, im dummy. But how write for Windows?

**Comment by sadovnychyi** [comment]
@scriptBoris how to write that executable path config? It's same on all platforms -- Settings / Packages / autocomplete-python, OR edit your atom's config.cson.
