### ISSUE TITLE
[Feature Request]Set and memoize per-project python paths manually

### ISSUE THREAD

**Issue by wonderbeyond** [autocomplete-python/autocomplete-python#321]
Only global settings of **Python Executable Paths** and **Extra Paths For Packages** don't work for all projects, even we can use variable substitution.

So why not support per-project settings for alternative.

**Comment by wonderbeyond** [comment]
I've been using [atom-project-manager](https://github.com/danielbrodin/atom-project-manager) for years, which provide easy access to all projects. It maintains all project settings in `~/.atom/projects.cson`, every project has its [specific settings](https://github.com/danielbrodin/atom-project-manager#project-settings)(e.g. title, paths, icon...).

It would be awesome if **Project Manager** can be a provider to other packages to store their own per-project settings(or state).

**Comment by sadovnychyi** [comment]
I would rather wait for official support from Atom.

There's a "settings" object which "Enables you to set project specific
settings. Everything that goes in the config.cson file can go here. It also
supports scoped settings." – why not just use that to configure
autocomplete-python for each project?

**Comment by wonderbeyond** [comment]
Oh I've missed the point that **Project Manager** has such a "settings" object for overriding any global settings. Thank you!

So all we need is a nice UI in Atom's **Settings View**, which let us switch between **Global mode** and **Project Mode**, with almost the same editing widgets.
Do you think the official support of this feature is expectable?

**Comment by wonderbeyond** [comment]
> why not just use that to configure autocomplete-python for each project?

However, according to my latest experience, this feature of **PM** is implicit and buggy, I've gave up using it.

**Comment by sadovnychyi** [comment]
You can track it here https://github.com/atom/atom/issues/5168 and there's couple of options from non-core packages.

Did you consider creating symlinks in each project pointing on desired python executable, and then just point your setting on that symlink for all projects?

**Comment by wonderbeyond** [comment]
> Did you consider creating symlinks in each project pointing on desired python executable, and then just point your setting on that symlink for all projects?

Good idea! It works.

Thanks for your tips!
