### ISSUE TITLE
Could not find platform independent libraries 

### ISSUE THREAD

**Issue by daliborb20** [autocomplete-python/autocomplete-python#326]
autocomplete-python worked flawlessly for a two months on Debian, now I am running on problems:

Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]

autocomplete-python traceback output:
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'

**Comment by sadovnychyi** [comment]
https://stackoverflow.com/questions/38132755/importerror-no-module-named-encodings

**Comment by daliborb20** [comment]
I have tried that. But unfortunately doesn't work.
