### ISSUE TITLE
Errors raised on typing in buildout project

### ISSUE THREAD

**Issue by MarloweW** [autocomplete-python/autocomplete-python#329]
### Prerequisites

* [X] Please make sure to properly [configure](https://github.com/autocomplete-python/autocomplete-python#configuration) plugin first if you simply cannot see any completions.
* [X] It's always helpful if you include debug logs with your issue:
  * Go to package settings to enable them
  ![image](https://cloud.githubusercontent.com/assets/193864/19852051/01e4e45c-9f9c-11e6-9480-dd22147c82b3.png)
  * Open `dev tools` using command palette and you should see some `autocomplete-python` records in console tab. This will include parts of your code – make sure to remove everything you don't want to share.

### Steps to Reproduce

1. I have a [buildout](https://github.com/buildout/buildout) project.
2. Errors are raised on typing in this project:
```autocomplete-python: autocomplete-python traceback output: Traceback (most recent call last):
  File "/Users/chichi/.atom/packages/autocomplete-python/lib/completion.py", line 374, in watch
    self._process_request(self._input.readline())
  File "/Users/chichi/.atom/packages/autocomplete-python/lib/completion.py", line 363, in _process_request
    request.get('prefix', '')))
  File "/Users/chichi/.atom/packages/autocomplete-python/lib/completion.py", line 151, in _serialize_completions
    'rightLabel': self._additional_info(completion)
  File "/Users/chichi/.atom/packages/autocomplete-python/lib/completion.py", line 40, in _additional_info
    if completion._definition is None:
AttributeError: 'Completion' object has no attribute '_definition'


log.coffee [sm]:5 autocomplete-python: Forcing to resolve 1 promises
log.coffee [sm]:5 autocomplete-python: Serializing request to be sent to Jedi ```

**Comment by brennv** [comment]
Not exactly sure if this is the right fix but this is my current workaround https://github.com/autocomplete-python/autocomplete-python/pull/330

**Comment by sadovnychyi** [comment]
Thanks for a fix, just pushed a new version.
