### ISSUE TITLE
Suggestion Priority: Function parameters first while typing inside parenthesis.

### ISSUE THREAD

**Issue by shh6242** [autocomplete-python/autocomplete-python#334]
Hi there, I really appreciate you to provide and maintain this awesome package.
Here is my problem.
### Steps to Reproduce
![parameters_priority](https://user-images.githubusercontent.com/30017764/29306928-a0f100c8-81da-11e7-819f-e5b99e5b1e86.gif)
1. [First Step]
Type a function or method.
(complete manually or use autocomplete <TAB>)
2. [Second Step]
Open parenthesis... wait

**Expected behavior:** 
Suggest parameter(s) of the function called first on the popup.

**Actual behavior:** [What actually happened]
Suggest in lexicographical order.

I thought this is something like option-dependent or machine-dependent problem.
So I tried resetting $USERPROFILE$\.atom but still get the lexicographically ordered suggestion.

**Comment by sadovnychyi** [comment]
Yeah, we don't have any ordering from Jedi right now. But should be easy to
boost each function argument.

**Comment by shh6242** [comment]
So this is not a bug... Thanks! 
BTW I think Suggestion Priority could be one possible solution for the on-going tooltip implementation.
because it won't need to develop another popup so not interrupting any of linter UI.
