### ISSUE TITLE
Don't make suggestions based on zero characters

### ISSUE THREAD

**Issue by willwhitney** [autocomplete-python/autocomplete-python#339]
In what possible situation would I want you to suggest `abs` based on _zero characters_ of prefix?

![image](https://user-images.githubusercontent.com/597829/30491421-36b2637a-9a0b-11e7-976f-33ba30b623b8.png)

**Comment by sadovnychyi** [comment]
From x import y

**Comment by sadovnychyi** [comment]
You can configure it using a regexp in settings anyway.

**Comment by willwhitney** [comment]
you're saying, you think that listing every variable in the universe after a space is the correct behavior? 

also, why not pay attention to the _global Atom setting_ that controls this?

**Comment by sadovnychyi** [comment]
Not in the universe, but in current scope -- yes. It's very useful to explore unfamiliar APIs by just typing `something.`.

I guess you are mentioning Minimum Word Length setting from autocomplete-plus, which states that it may not affect external providers.

You can change regex to trigger autocompletion to e.g. `([. (]|[a-zA-Z_][a-zA-Z0-9_]{3,})` or whatever pattern you prefer.
