### ISSUE TITLE
when i put ( ) it is auto filling with unwanted text

### ISSUE THREAD

**Issue by e11i0t23** [autocomplete-python/autocomplete-python#350]
when coding and using brackets i am getting text auto filled in please see below for examples please can someone help tell me how to fix this thanks

examples:

- "print ()"  is filling to "print (value, sep=' ', end='n', file=sys.stdout, flush=False)
and
- "for i in range()" is filling to "for i in range(start, stop=None, step=1)"

**Comment by sadovnychyi** [comment]
Disable argument completion in settings.

**Comment by e11i0t23** [comment]
Thanks for your help i now feel so dumb for not reading properly but thanks anyway
