### ISSUE TITLE
Suppress .self suggestion when writing comments

### ISSUE THREAD

**Issue by Hoseung** [autocomplete-python/autocomplete-python#386]
This not a bug report but a suggestion. 

On putting a period at the end of a sentence in the comment, .self appears as a autocomplete suggestion. I understand that this is very natural, but I doubt having .self as a suggestion is very useful (Of course it is useful when I'm writing a custom class). 

If there were a way to "tune" or "filter" the suggestions, that would be great.
I don't expect anything to be done about this shortly as it is not urgent. But I was curious what others think about it.

![selection_021](https://user-images.githubusercontent.com/3907106/43242217-b307681e-90da-11e8-9fac-dc0fde1fb19d.png)

Anyways, thanks for the wonderful plug-in :)

**Comment by sadovnychyi** [comment]
I'm pretty sure this is one of Atom's built in snippets and not autocomplete-python. Not sure how you can remove the specific one, but you could completely disable autocomplete-snippets plugin.

**Comment by gilbertohasnofb** [comment]
@Hoseung I solved this by installing `auotcomplete-plus` and adding `.comment, .string.quoted, .text.plain` to the Scope Blacklist field in its settings. Now I don't get annoying autocomplete suggestions when I am typing comments or plain text files.
