### ISSUE TITLE
autocomplete-python isn't working with python 3.10 and jedi 0.18

### ISSUE THREAD

**Issue by RogueDot** [autocomplete-python/autocomplete-python#462]
I downloaded Jedi and Python 3.10 and autocomplete-python isn't working...
Even after configuration it still doesn't work.
Any help would be appreciated...
![Screenshot (40)](https://user-images.githubusercontent.com/72721501/138082733-7b70adde-41d7-47b4-aaed-f42cc8aeb232.png)

**Comment by jrobinson3k1** [comment]
@RogueDot : If this is still something you'd use, I have a PR open that makes this package work with jedi 0.18. I might publish my fork if it doesn't look like the owner is going to merge. It'd be nice to have a sanity check so I know I didn't only fix it for my particular work environment though.

**Comment by RogueDot** [comment]
I would
